// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALtZCWccFai51pZr4ShMbspdr7HxranxU',
    appId: '1:318790376010:web:8e15f3f803367670d564b3',
    messagingSenderId: '318790376010',
    projectId: 'ff-quiz-app',
    authDomain: 'ff-quiz-app.firebaseapp.com',
    storageBucket: 'ff-quiz-app.appspot.com',
    measurementId: 'G-BKHKMQFDN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5vlSuqvDGu4PulimTIXnHH9DUJ5PY2-c',
    appId: '1:318790376010:android:f153a19b7cb7f393d564b3',
    messagingSenderId: '318790376010',
    projectId: 'ff-quiz-app',
    storageBucket: 'ff-quiz-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOUZBPdoCIgqPko50gx9faxeJdKt2Ke6s',
    appId: '1:318790376010:ios:033b978978f9824fd564b3',
    messagingSenderId: '318790376010',
    projectId: 'ff-quiz-app',
    storageBucket: 'ff-quiz-app.appspot.com',
    iosBundleId: 'com.example.quizAppFb',
  );
}
